#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset

postgres_ready() {
python << END
import sys

import psycopg2

try:
    psycopg2.connect(
        user="tofunmi",
        password="toffy123",
        host="db",
        port="5432",
        dbname="seepspring"
    )
except psycopg2.OperationalError as e:
    print(e)
    print(f"psycopg2.connect(dbname='{dbname}', user='{user}', password='{password}', host='{host}', port='{port}')")
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
    echo "sd"
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"