# Generated by Django 3.2.8 on 2022-08-30 17:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_userloan_loan_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userloan',
            old_name='amount',
            new_name='amount_disbursed',
        ),
        migrations.AddField(
            model_name='userloan',
            name='amount_requested',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='userloan',
            name='loan_request_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DISBURSED', 'DISBURSED'), ('LATE', 'LATE'), ('SETTLED', 'SETTLED'), ('DISAPPROVED', 'DISAPPROVED'), ('PART SETTLEMENT', 'PART SETTLEMENT')], default='PENDING', max_length=225),
        ),
        migrations.CreateModel(
            name='InterestBreakdown',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_1', models.CharField(blank=True, max_length=300, null=True)),
                ('text_2', models.CharField(blank=True, max_length=300, null=True)),
                ('text_4', models.CharField(blank=True, max_length=300, null=True)),
                ('text_5', models.CharField(blank=True, max_length=300, null=True)),
                ('text_6', models.CharField(blank=True, max_length=300, null=True)),
                ('text_7', models.CharField(blank=True, max_length=300, null=True)),
                ('text_8', models.CharField(blank=True, max_length=300, null=True)),
                ('text_9', models.CharField(blank=True, max_length=300, null=True)),
                ('text_10', models.CharField(blank=True, max_length=300, null=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.interest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
