# Generated by Django 3.2.8 on 2022-08-30 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20220830_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloan',
            name='loan_due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userloan',
            name='loan_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userloan',
            name='loan_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userloan',
            name='loan_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
