# Generated by Django 3.2.8 on 2022-08-30 20:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20220830_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPurpose',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userloan',
            name='loan_purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.loanpurpose'),
        ),
    ]
