# Generated by Django 3.2.8 on 2022-08-31 01:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20220831_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePagePromotion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('promotion_type', models.CharField(blank=True, max_length=300, null=True)),
                ('text_1', models.CharField(blank=True, max_length=300, null=True)),
                ('text_2', models.CharField(blank=True, max_length=300, null=True)),
                ('text_3', models.CharField(blank=True, max_length=300, null=True)),
                ('text_4', models.CharField(blank=True, max_length=300, null=True)),
                ('text_5', models.CharField(blank=True, max_length=300, null=True)),
                ('text_6', models.CharField(blank=True, max_length=300, null=True)),
                ('text_7', models.CharField(blank=True, max_length=300, null=True)),
                ('text_8', models.CharField(blank=True, max_length=300, null=True)),
                ('text_9', models.CharField(blank=True, max_length=300, null=True)),
                ('text_10', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepaymentGuide',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('repayment_type', models.CharField(blank=True, max_length=300, null=True)),
                ('text_1', models.CharField(blank=True, max_length=300, null=True)),
                ('text_2', models.CharField(blank=True, max_length=300, null=True)),
                ('text_3', models.CharField(blank=True, max_length=300, null=True)),
                ('text_4', models.CharField(blank=True, max_length=300, null=True)),
                ('text_5', models.CharField(blank=True, max_length=300, null=True)),
                ('text_6', models.CharField(blank=True, max_length=300, null=True)),
                ('text_7', models.CharField(blank=True, max_length=300, null=True)),
                ('text_8', models.CharField(blank=True, max_length=300, null=True)),
                ('text_9', models.CharField(blank=True, max_length=300, null=True)),
                ('text_10', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='guarntee',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guarntee',
            name='text_3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='interestbreakdown',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanlevel',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanpurpose',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
