# Generated by Django 3.2.8 on 2022-09-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_auto_20220831_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=28.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='interest',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='interest',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=7.5, max_digits=11),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='userloan',
            name='amount_disbursed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='userloan',
            name='amount_left',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='userloan',
            name='amount_requested',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
