# Generated by Django 3.2.8 on 2022-09-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_auto_20220901_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='editable_repayment_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
