# Generated by Django 3.2.8 on 2022-09-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_loanrepayment_editable_repayment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloan',
            name='accumulated_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
    ]
