# Generated by Django 3.2.8 on 2022-09-17 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_userloan_accumulated_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloan',
            name='last_accumulate_date',
            field=models.DateField(default=datetime.date(2022, 9, 17)),
        ),
    ]
