# Generated by Django 3.2.8 on 2022-11-17 07:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_userloan_last_accumulate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloan',
            name='last_accumulate_date',
            field=models.DateField(default=datetime.date(2022, 11, 17)),
        ),
        migrations.CreateModel(
            name='LoanPageInformationSlider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('number', models.IntegerField(blank=True, default=1, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('image_url', models.URLField(blank=True, max_length=300, null=True)),
                ('interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.interest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
