# Generated by Django 3.2.8 on 2022-11-17 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customuser_bvn_phone_number'),
        ('loan', '0013_singlepromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloan',
            name='account_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bankaccountdetails'),
        ),
    ]
