# Generated by Django 3.2.8 on 2023-01-19 11:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0016_alter_userloan_last_accumulate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloan',
            name='last_accumulate_date',
            field=models.DateField(default=datetime.date(2023, 1, 19)),
        ),
        migrations.CreateModel(
            name='AmountDisbursed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('amount_disbursed', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('disbursement_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_refernce', models.CharField(max_length=255)),
                ('editable_disbursement_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user_loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.userloan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
