# Generated by Django 3.2.8 on 2023-01-20 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0017_auto_20230119_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloan',
            name='late_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userloan',
            name='loan_repayment_status',
            field=models.CharField(choices=[('LATE', 'LATE'), ('SETTLED', 'SETTLED'), ('PART SETTLEMENT', 'PART SETTLEMENT'), ('ONGOING', 'ONGOING')], default='ONGOING', max_length=225),
        ),
        migrations.AlterField(
            model_name='userloan',
            name='last_accumulate_date',
            field=models.DateField(default=datetime.date(2023, 1, 20)),
        ),
        migrations.AlterField(
            model_name='userloan',
            name='loan_request_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DISBURSED', 'DISBURSED'), ('DISAPPROVED', 'DISAPPROVED')], default='PENDING', max_length=225),
        ),
    ]
