# Generated by Django 3.2.8 on 2022-08-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmploymentDuration',
            new_name='NigerianBanks',
        ),
    ]
