# Generated by Django 3.2.8 on 2023-03-28 10:27
# Generated by Django 3.2.8 on 2023-03-24 14:26





import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bvn_phone_number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[accounts.models.validate_mobile_num], verbose_name='BVN phone number'),
        ),
    ]
