# Generated by Django 3.2.8 on 2022-08-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220815_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentduration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='salaryrange',
            name='user',
        ),
    ]
