# Generated by Django 3.2.8 on 2022-08-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useremploymentduration_usersalaryrange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number_of_children',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
