# Generated by Django 3.2.8 on 2022-08-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountdetails',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colleaguecontact',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmentduration',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employmentinformation',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salaryrange',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useremploymentduration',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersalaryrange',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
