# Generated by Django 3.2.8 on 2022-10-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentinformation',
            name='employment_duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employmentduration'),
        ),
        migrations.AlterField(
            model_name='employmentinformation',
            name='salary_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.salaryrange'),
        ),
    ]
