# Generated by Django 3.2.8 on 2022-11-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_otpphone_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpphone',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
