# Generated by Django 3.2.8 on 2022-11-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_otpphone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lga_of_residence',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state_of_residence',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
