# Generated by Django 3.2.8 on 2022-12-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customuser_bvn_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('superadmin', 'superadmin'), ('accountant', 'accountant'), ('reconciliation_officer', 'reconciliation_officer'), ('customer', 'customer')], default='customer', max_length=30),
        ),
    ]
