#levels
LEVEL_1 = 1
LEVEL_2 = 2
LEVEL_3 = 3
LEVEL_4 = 4

LEVEL_CHOICES = (
    (LEVEL_1, LEVEL_1),
    (LEVEL_2, LEVEL_2),
    (LEVEL_3, LEVEL_3),
    (LEVEL_4, LEVEL_4),

)

#loan rewuest status

PENDING = "PENDING"
DISBURSED = "DISBURSED"
LATE = "LATE"
SETTLED = "SETTLED"
DISAPPROVED = "DISAPPROVED"
PART_SETTLEMENT = "PART SETTLEMENT"
ONGOING = "ONGOING"



LOAN_REQUEST_STATUS = (
    (PENDING, PENDING),
    (DISBURSED, DISBURSED),
    (DISAPPROVED, DISAPPROVED),
)

LOAN_REPAYMENT_STATUS = (
    (LATE, LATE),
    (SETTLED, SETTLED),
    (PART_SETTLEMENT, PART_SETTLEMENT),
    (ONGOING, ONGOING),

)



MAX_DIGITS = 11
DECIMAL_PLACES = 2