name: Deploy to Linux Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up SSH connection to server
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
          
      # - name: Copy files to server
        # run: ls
        # run: echo "+++++++++++++++++++++++=="

        # run: sudo scp -r . ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/seepspring
      - name: Install ssh-keyscan
      run: sudo apt-get install -y ssh-keyscan

      - name: Scan server key
        run: ssh-keyscan ${{ secrets.SERVER_HOST }} ~/.ssh/known_hosts

      - name: Connect to server and deploy code
        run: |
          ssh tofunmi@${{ secrets.SERVER_HOST }} << EOF
            cd /seepspring
            docker compose down

          EOF
          
    env:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
