name: Deploy to Linux Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up SSH connection to server
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
          
      - name: Copy files to server
        run: scp -r . ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:/seepspring
        
      - name: Connect to server and deploy code
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << EOF
            cd /seepspring
            docker compose down
            # git pull origin main
            # Additional commands to deploy the code
          EOF
          
    env:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
